version: '3.6'

services:
  backend:
    build:
      context: ./backend
      target: ${DOCKER_TARGET}
      args:
        - APPLICATION_ENV=${APPLICATION_ENV}
    container_name: upm-movies-api
    env_file:
      - .env
    environment:
      APPLICATION_ENV: ${APPLICATION_ENV}
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ./backend:/srv/backend
